### ISSUE TITLE
Questions about multi-node deepspeed launcher

### ISSUE THREAD

**Issue by vealocia** [JialianW/GRiT#3]
Hi, @JialianW! Thanks for your wonderful work!
I try to run GRiT on 4 nodes & 32 GPUs with following command:
```
python train_deepspeed.py --num-machines 4 --num-gpus-per-machine 8 --config-file configs/GRiT_B_ObjectDet.yaml --output-dir-name ./output/grit_b_objectdet
```
However, I notice that only one GPU is used on each node.
In implementation, there is no ```mp.spawn``` in [multi-node deepspeed launcher](https://github.com/JialianW/GRiT/blob/39b33dbc0900e4be0458af14597fcb1a82d933bb/lauch_deepspeed.py#L154), is this the reason and is there any plan to fix this?

**Comment by JialianW** [comment]
Thanks for your interest in GRiT.

When we train on our cluster, our cluster itself does the multi-processes creation for us. That's why we didn't use mp.spawn in the code. In order to make it work for you, you may use mpirun or other multi-process manager tools to start the training script
 for multi-nodes. Sorry for the missing information in the readme instructions, we were supposed to update the readme to let people be aware of this.
